### ISSUE TITLE
Can you add port # as an option?

### ISSUE THREAD

**Issue by travisghansen** [krauskopf/node-red-contrib-avr-yamaha#1]
One of my receivers uses port `49154` as the port for `desc.xml`  Any chance that can become a config option on a per-receiver basis?

Also, due to the failed web-request node red completely dies so it probably needs a bit more bullet-proofing in place:

```
19 Sep 03:48:20 - TypeError: Cannot read property 'root' of null
    at /data/node_modules/node-red-contrib-avr-yamaha/avr-yamaha.js:248:36
    at Parser.<anonymous> (/data/node_modules/node-red-contrib-avr-yamaha/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (/data/node_modules/node-red-contrib-avr-yamaha/node_modules/xml2js/lib/xml2js.js:499:16)
    at Parser.parseString (/data/node_modules/node-red-contrib-avr-yamaha/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/data/node_modules/node-red-contrib-avr-yamaha/node_modules/xml2js/lib/xml2js.js:540:19)
    at IncomingMessage.<anonymous> (/data/node_modules/node-red-contrib-avr-yamaha/avr-yamaha.js:242:15)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by krauskopf** [comment]
Thanks for the feedback.

Please have a look at version 0.6.0

**Comment by travisghansen** [comment]
Cool I'll try it out a bit later and let you know how it works.  I've got a mix of models so it should be a good test.  Thanks!

**Comment by travisghansen** [comment]
This is good:

```
19 Sep 17:36:00 - [info] [avr-yamaha:34d7823d.26ce4e] Failed to get device description with error: Error: connect ECONNREFUSED 172.29.50.122:8080
```

I've got the node updated with the appropriate port and it worked great.  I'll add the others on my network to the mix and report back just to make sure there's not something crazy going on with multiples.

**Comment by travisghansen** [comment]
That seems to work.  Thanks!

**Comment by krauskopf** [comment]
Thanks for testing. Do you mind listing the model types, that you used? Would be helpfull to have a list of verified models.

**Comment by travisghansen** [comment]
Here are the models I have:
- TSR-5790 (this is the one with the strange port #)
- RX-A740
- HTR-4065

**Comment by krauskopf** [comment]
Thx! Added the models to readme. Might be useful for other users.
